import type { AuditLog } from '@prisma/client';

export type AuditLogDTO = AuditLog;

export type AuditAction =
  | 'conversation.create'
  | 'conversation.update'
  | 'conversation.delete'
  | 'message.create'
  | 'message.delete'
  | 'recruiter.create'
  | 'recruiter.update'
  | 'recruiter.delete'
  | 'company.create'
  | 'company.update'
  | 'company.delete'
  | 'job.create'
  | 'job.update'
  | 'job.delete'
  | 'job.analyze'
  | 'application.create'
  | 'application.update'
  | 'application.delete'
  | 'interview.create'
  | 'interview.update'
  | 'interview.delete'
  | 'interview.prep'
  | 'note.create'
  | 'note.update'
  | 'note.delete'
  | 'reminder.create'
  | 'reminder.update'
  | 'reminder.delete'
  | 'reminder.due'
  | 'profile.update'
  | 'ai.draft'
  | 'ai.analyze'
  | 'ai.summarize'
  | 'auth.login'
  | 'auth.signup';
